import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';
import '../../../core/services/firebase_auth_service.dart';
import '../../../core/providers/recurring_transaction_provider.dart';
import '../../../core/providers/unified_provider_v2.dart';
import '../../../core/theme/theme_provider.dart';
import '../../../shared/models/recurring_transaction_model.dart';
import '../../../shared/models/account_model.dart';
import '../../../modules/transactions/models/recurring_frequency.dart';
import '../../../l10n/app_localizations.dart';
import '../../../shared/utils/currency_utils.dart';
import '../../../shared/widgets/thousands_separator_input_formatter.dart';

/// Add Subscription Form - Single Step Form (like Budget Form)
class AddSubscriptionForm extends StatefulWidget {
  final VoidCallback? onSubscriptionSaved;
  final double? initialAmount;
  final String? initialAccountId;

  const AddSubscriptionForm({
    super.key,
    this.onSubscriptionSaved,
    this.initialAmount,
    this.initialAccountId,
  });

  @override
  State<AddSubscriptionForm> createState() => _AddSubscriptionFormState();
}

class _AddSubscriptionFormState extends State<AddSubscriptionForm> {
  final _formKey = GlobalKey<FormState>();
  
  // Form fields
  final _nameController = TextEditingController();
  final _amountController = TextEditingController();
  final FocusNode _nameFocusNode = FocusNode();
  final FocusNode _amountFocusNode = FocusNode();
  
  RecurringCategory _selectedCategory = RecurringCategory.subscription;
  RecurringFrequency _selectedFrequency = RecurringFrequency.monthly;
  DateTime _startDate = DateTime.now();
  DateTime? _endDate;
  bool _hasEndDate = false;
  String? _selectedAccountId;
  
  bool _isSaving = false;

  bool _hasPrefilled = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    
    // Prefill only once
    if (!_hasPrefilled) {
      _hasPrefilled = true;
      
      // Prefill amount if provided
      if (widget.initialAmount != null && widget.initialAmount! > 0) {
        final themeProvider = Provider.of<ThemeProvider>(context, listen: false);
        final formattedAmount = CurrencyUtils.formatAmountWithoutSymbol(
          widget.initialAmount!,
          themeProvider.currency,
        );
        _amountController.text = formattedAmount;
      }
      
      // Prefill account if provided
      if (widget.initialAccountId != null && widget.initialAccountId!.isNotEmpty) {
        _selectedAccountId = widget.initialAccountId;
      }
    }
  }

  @override
  void dispose() {
    _nameController.dispose();
    _amountController.dispose();
    _nameFocusNode.dispose();
    _amountFocusNode.dispose();
    super.dispose();
  }

  bool _canSave() {
    final themeProvider = Provider.of<ThemeProvider>(context, listen: false);
    final amount = ThousandsSeparatorInputFormatter.parseLocaleDouble(
      _amountController.text,
      themeProvider.currency.locale,
    );
    return _nameController.text.isNotEmpty &&
        _amountController.text.isNotEmpty &&
        amount != null &&
        amount > 0 &&
        _selectedAccountId != null &&
        !_isSaving;
  }

  Future<void> _saveSubscription() async {
    if (!_canSave()) {
      return;
    }

    setState(() => _isSaving = true);
    try {
      final themeProvider = Provider.of<ThemeProvider>(context, listen: false);
      final locale = themeProvider.currency.locale;
      final amount = ThousandsSeparatorInputFormatter.parseLocaleDouble(
        _amountController.text,
        locale,
      );
      
      if (amount == null || amount <= 0) {
        setState(() => _isSaving = false);
        return;
      }

      final userId = FirebaseAuthService.currentUserId;
      if (userId == null) {
        setState(() => _isSaving = false);
        return;
      }

      final provider = Provider.of<RecurringTransactionProvider>(context, listen: false);
      
      final now = DateTime.now();
      final subscription = RecurringTransaction(
        id: '', // Will be generated by service
        userId: userId,
        name: _nameController.text.trim(),
        category: _selectedCategory,
        amount: amount,
        categoryId: _selectedCategory.name,
        accountId: _selectedAccountId!,
        frequency: _selectedFrequency,
        startDate: _startDate,
        endDate: _hasEndDate ? _endDate : null,
        isActive: true,
        lastExecutedDate: null,
        nextExecutionDate: null, // Will be calculated by provider
        description: null,
        notes: null,
        createdAt: now,
        updatedAt: now,
      );

      final id = await provider.createSubscription(subscription);
      
      if (id == null) {
        throw Exception('Failed to create subscription');
      }

      _nameController.clear();
      _amountController.clear();
      setState(() {
        _selectedCategory = RecurringCategory.subscription;
        _selectedFrequency = RecurringFrequency.monthly;
        _startDate = DateTime.now();
        _endDate = null;
        _hasEndDate = false;
        _selectedAccountId = null;
        _isSaving = false;
      });

      if (context.mounted) {
        final l10n = AppLocalizations.of(context)!;
        Navigator.pop(context);
        widget.onSubscriptionSaved?.call();
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(l10n.subscriptionAdded),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e) {
      setState(() => _isSaving = false);
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('${AppLocalizations.of(context)!.errorOccurred}: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final l10n = AppLocalizations.of(context)!;
    final themeProvider = Provider.of<ThemeProvider>(context, listen: false);

    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: isDark ? const Color(0xFF1C1C1E) : Colors.white,
        borderRadius: const BorderRadius.only(
          topLeft: Radius.circular(20),
          topRight: Radius.circular(20),
        ),
      ),
      child: SingleChildScrollView(
        padding: EdgeInsets.only(
          bottom: MediaQuery.of(context).viewInsets.bottom,
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Center(
              child: Container(
                width: 40,
                height: 4,
                decoration: BoxDecoration(
                  color: const Color(0xFF8E8E93),
                  borderRadius: BorderRadius.circular(2),
                ),
              ),
            ),
            const SizedBox(height: 20),
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: isDark
                        ? const Color(0xFF38383A)
                        : const Color(0xFFE5E5EA),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Icon(
                    Icons.subscriptions_outlined,
                    color: isDark ? Colors.white : const Color(0xFF6D6D70),
                    size: 20,
                  ),
                ),
                const SizedBox(width: 12),
                Text(
                  l10n.addSubscription ?? 'Yeni Abonelik',
                  style: GoogleFonts.inter(
                    fontSize: 18,
                    fontWeight: FontWeight.w600,
                    color: isDark ? Colors.white : Colors.black,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 20),
            
            // Name input
            Text(
              l10n.subscriptionName ?? 'Abonelik Adı',
              style: GoogleFonts.inter(
                fontSize: 14,
                fontWeight: FontWeight.w600,
                color: isDark ? Colors.white : const Color(0xFF1C1C1E),
              ),
            ),
            const SizedBox(height: 8),
            TextField(
              controller: _nameController,
              focusNode: _nameFocusNode,
              textInputAction: TextInputAction.next,
              style: GoogleFonts.inter(
                fontSize: 16,
                color: isDark ? Colors.white : Colors.black,
              ),
              decoration: InputDecoration(
                hintText: l10n.subscriptionExample,
                hintStyle: GoogleFonts.inter(
                  color: isDark
                      ? const Color(0xFF8E8E93)
                      : const Color(0xFF6D6D70),
                ),
                filled: true,
                fillColor: isDark
                    ? const Color(0xFF2C2C2E)
                    : const Color(0xFFF2F2F7),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: BorderSide(
                    color: isDark
                        ? const Color(0xFF38383A)
                        : const Color(0xFFE5E5EA),
                    width: 1.2,
                  ),
                ),
                enabledBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: BorderSide(
                    color: isDark
                        ? const Color(0xFF38383A)
                        : const Color(0xFFE5E5EA),
                    width: 1.2,
                  ),
                ),
                focusedBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: BorderSide(
                    color: isDark
                        ? const Color(0xFF38383A)
                        : const Color(0xFFE5E5EA),
                    width: 2,
                  ),
                ),
              ),
              onSubmitted: (_) {
                FocusScope.of(context).requestFocus(_amountFocusNode);
              },
              onChanged: (_) => setState(() {}),
            ),
            const SizedBox(height: 20),
            
            // Category selection (without icons)
            Text(
              l10n.category ?? 'Kategori',
              style: GoogleFonts.inter(
                fontSize: 14,
                fontWeight: FontWeight.w600,
                color: isDark ? Colors.white : const Color(0xFF1C1C1E),
              ),
            ),
            const SizedBox(height: 12),
            SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: Row(
                children: RecurringCategory.values.map((category) {
                  final isSelected = _selectedCategory == category;
                  return GestureDetector(
                    onTap: () {
                      HapticFeedback.lightImpact();
                      setState(() => _selectedCategory = category);
                    },
                    child: Container(
                      margin: const EdgeInsets.only(right: 12),
                      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                      decoration: BoxDecoration(
                        color: isSelected
                            ? const Color(0xFF007AFF)
                            : (isDark ? const Color(0xFF2C2C2E) : const Color(0xFFF2F2F7)),
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(
                          color: isSelected
                              ? const Color(0xFF007AFF)
                              : (isDark ? const Color(0xFF3A3A3C) : const Color(0xFFE5E5EA)),
                          width: isSelected ? 2 : 1.2,
                        ),
                      ),
                      child: Text(
                        category.getName(l10n),
                        style: GoogleFonts.inter(
                          fontSize: 14,
                          fontWeight: isSelected ? FontWeight.w600 : FontWeight.w500,
                          color: isSelected
                              ? Colors.white
                              : (isDark ? Colors.white : Colors.black),
                        ),
                      ),
                    ),
                  );
                }).toList(),
              ),
            ),
            const SizedBox(height: 20),
            
            // Frequency selection
            Text(
              l10n.frequency,
              style: GoogleFonts.inter(
                fontSize: 14,
                fontWeight: FontWeight.w600,
                color: isDark ? Colors.white : const Color(0xFF1C1C1E),
              ),
            ),
            const SizedBox(height: 12),
            Container(
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(12),
                color: isDark ? const Color(0xFF2C2C2E) : const Color(0xFFF2F2F7),
                border: Border.all(
                  color: isDark ? const Color(0xFF38383A) : const Color(0xFFE5E5EA),
                  width: 1.2,
                ),
              ),
              child: Row(
                children: RecurringFrequency.values.map((frequency) {
                  final isSelected = _selectedFrequency == frequency;
                  return Expanded(
                    child: GestureDetector(
                      onTap: () {
                        HapticFeedback.lightImpact();
                        setState(() => _selectedFrequency = frequency);
                      },
                      child: Container(
                        padding: const EdgeInsets.symmetric(vertical: 12),
                        decoration: BoxDecoration(
                          color: isSelected
                              ? const Color(0xFF007AFF)
                              : Colors.transparent,
                          borderRadius: BorderRadius.circular(10),
                        ),
                        child: Center(
                          child: Text(
                            frequency.getDisplayName(l10n),
                            style: GoogleFonts.inter(
                              fontSize: 14,
                              fontWeight: isSelected ? FontWeight.w600 : FontWeight.w500,
                              color: isSelected
                                  ? Colors.white
                                  : (isDark ? Colors.white : Colors.black),
                            ),
                          ),
                        ),
                      ),
                    ),
                  );
                }).toList(),
              ),
            ),
            const SizedBox(height: 20),
            
            // Amount input
            Text(
              '${l10n.amount ?? 'Tutar'} (${_selectedFrequency.getDisplayName(l10n)})',
              style: GoogleFonts.inter(
                fontSize: 14,
                fontWeight: FontWeight.w600,
                color: isDark ? Colors.white : const Color(0xFF1C1C1E),
              ),
            ),
            const SizedBox(height: 8),
            Consumer<ThemeProvider>(
              builder: (context, themeProvider, child) {
                final currencySymbol = CurrencyUtils.getSymbolForCurrency(themeProvider.currency);
                final localeString = themeProvider.currency.locale;
                final locale = Locale(localeString.split('_')[0]);
                final isTurkish = locale.languageCode == 'tr';
                
                return TextField(
                  controller: _amountController,
                  focusNode: _amountFocusNode,
                  keyboardType: TextInputType.numberWithOptions(decimal: true),
                  textInputAction: TextInputAction.next,
                  inputFormatters: [
                    ThousandsSeparatorInputFormatter(locale: localeString),
                  ],
                  style: GoogleFonts.inter(
                    fontSize: 16,
                    color: isDark ? Colors.white : Colors.black,
                  ),
                  decoration: InputDecoration(
                    hintText: isTurkish ? '0,00' : '0.00',
                    prefixText: '$currencySymbol ',
                    prefixStyle: GoogleFonts.inter(
                      fontSize: 16,
                      color: isDark ? Colors.white : Colors.black,
                    ),
                    hintStyle: GoogleFonts.inter(
                      color: isDark
                          ? const Color(0xFF8E8E93)
                          : const Color(0xFF6D6D70),
                    ),
                    filled: true,
                    fillColor: isDark
                        ? const Color(0xFF2C2C2E)
                        : const Color(0xFFF2F2F7),
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(12),
                      borderSide: BorderSide(
                        color: isDark
                            ? const Color(0xFF38383A)
                            : const Color(0xFFE5E5EA),
                        width: 1.2,
                      ),
                    ),
                    enabledBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(12),
                      borderSide: BorderSide(
                        color: isDark
                            ? const Color(0xFF38383A)
                            : const Color(0xFFE5E5EA),
                        width: 1.2,
                      ),
                    ),
                    focusedBorder: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(12),
                      borderSide: BorderSide(
                        color: isDark
                            ? const Color(0xFF38383A)
                            : const Color(0xFFE5E5EA),
                        width: 2,
                      ),
                    ),
                  ),
                  onChanged: (_) => setState(() {}),
                );
              },
            ),
            const SizedBox(height: 20),
            
            // Start date
            Text(
              l10n.startDate,
              style: GoogleFonts.inter(
                fontSize: 14,
                fontWeight: FontWeight.w600,
                color: isDark ? Colors.white : const Color(0xFF1C1C1E),
              ),
            ),
            const SizedBox(height: 8),
            GestureDetector(
              onTap: () async {
                final DateTime? pickedDate = await showDatePicker(
                  context: context,
                  initialDate: _startDate,
                  firstDate: DateTime(2020),
                  lastDate: DateTime(2030),
                  builder: (context, child) {
                    return Theme(
                      data: Theme.of(context).copyWith(
                        colorScheme: ColorScheme.light(
                          primary: const Color(0xFF007AFF),
                          onPrimary: Colors.white,
                          surface: isDark ? const Color(0xFF1C1C1E) : Colors.white,
                          onSurface: isDark ? Colors.white : Colors.black,
                        ),
                      ),
                      child: child!,
                    );
                  },
                );
                if (pickedDate != null && pickedDate != _startDate) {
                  setState(() {
                    _startDate = pickedDate;
                  });
                }
              },
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                decoration: BoxDecoration(
                  color: isDark ? const Color(0xFF2C2C2E) : const Color(0xFFF2F2F7),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(
                    color: isDark ? const Color(0xFF38383A) : const Color(0xFFE5E5EA),
                    width: 1.2,
                  ),
                ),
                child: Row(
                  children: [
                    Icon(
                      Icons.calendar_today,
                      color: isDark ? Colors.white : const Color(0xFF6D6D70),
                      size: 20,
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Text(
                        '${_startDate.day.toString().padLeft(2, '0')}/${_startDate.month.toString().padLeft(2, '0')}/${_startDate.year}',
                        style: GoogleFonts.inter(
                          fontSize: 16,
                          color: isDark ? Colors.white : Colors.black,
                        ),
                      ),
                    ),
                    Icon(
                      Icons.arrow_drop_down,
                      color: isDark ? Colors.white : const Color(0xFF6D6D70),
                      size: 20,
                    ),
                  ],
                ),
              ),
            ),
            
            // End date (optional)
            const SizedBox(height: 20),
            Row(
              children: [
                Checkbox(
                  value: _hasEndDate,
                  onChanged: (value) {
                    setState(() {
                      _hasEndDate = value ?? false;
                      if (!_hasEndDate) {
                        _endDate = null;
                      } else if (_endDate == null) {
                        _endDate = _startDate.add(const Duration(days: 365));
                      }
                    });
                  },
                ),
                Text(
                  l10n.endDateOptional,
                  style: GoogleFonts.inter(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                    color: isDark ? Colors.white : const Color(0xFF1C1C1E),
                  ),
                ),
              ],
            ),
            if (_hasEndDate) ...[
              const SizedBox(height: 8),
              GestureDetector(
                onTap: () async {
                  final DateTime? pickedDate = await showDatePicker(
                    context: context,
                    initialDate: _endDate ?? _startDate.add(const Duration(days: 365)),
                    firstDate: _startDate,
                    lastDate: DateTime(2030),
                    builder: (context, child) {
                      return Theme(
                        data: Theme.of(context).copyWith(
                          colorScheme: ColorScheme.light(
                            primary: const Color(0xFF007AFF),
                            onPrimary: Colors.white,
                            surface: isDark ? const Color(0xFF1C1C1E) : Colors.white,
                            onSurface: isDark ? Colors.white : Colors.black,
                          ),
                        ),
                        child: child!,
                      );
                    },
                  );
                  if (pickedDate != null && pickedDate != _endDate) {
                    setState(() {
                      _endDate = pickedDate;
                    });
                  }
                },
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                  decoration: BoxDecoration(
                    color: isDark ? const Color(0xFF2C2C2E) : const Color(0xFFF2F2F7),
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(
                      color: isDark ? const Color(0xFF38383A) : const Color(0xFFE5E5EA),
                      width: 1.2,
                    ),
                  ),
                  child: Row(
                    children: [
                      Icon(
                        Icons.calendar_today,
                        color: isDark ? Colors.white : const Color(0xFF6D6D70),
                        size: 20,
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: Text(
                          _endDate != null
                              ? '${_endDate!.day.toString().padLeft(2, '0')}/${_endDate!.month.toString().padLeft(2, '0')}/${_endDate!.year}'
                              : l10n.selectDate,
                          style: GoogleFonts.inter(
                            fontSize: 16,
                            color: isDark ? Colors.white : Colors.black,
                          ),
                        ),
                      ),
                      Icon(
                        Icons.arrow_drop_down,
                        color: isDark ? Colors.white : const Color(0xFF6D6D70),
                        size: 20,
                      ),
                    ],
                  ),
                ),
              ),
            ],
            const SizedBox(height: 20),
            
            // Account selection
            Text(
              l10n.selectAccount,
              style: GoogleFonts.inter(
                fontSize: 14,
                fontWeight: FontWeight.w600,
                color: isDark ? Colors.white : const Color(0xFF1C1C1E),
              ),
            ),
            const SizedBox(height: 12),
            Consumer<UnifiedProviderV2>(
              builder: (context, provider, child) {
                final accounts = provider.accounts.where((a) => a.isActive).toList();
                
                // Horizontal scrollable list
                return SizedBox(
                  height: 80,
                  child: ListView.builder(
                    scrollDirection: Axis.horizontal,
                    itemCount: accounts.length,
                    itemBuilder: (context, index) {
                      final account = accounts[index];
                      final isSelected = _selectedAccountId == account.id;
                      return Padding(
                        padding: EdgeInsets.only(
                          right: index < accounts.length - 1 ? 8 : 0,
                        ),
                        child: _buildAccountOption(
                          context: context,
                          account: account,
                          isSelected: isSelected,
                          l10n: l10n,
                          themeProvider: themeProvider,
                          isHorizontal: true,
                          onTap: () {
                            HapticFeedback.selectionClick();
                            setState(() => _selectedAccountId = account.id);
                          },
                        ),
                      );
                    },
                  ),
                );
              },
            ),
            const SizedBox(height: 24),
            
            // Action buttons
            Row(
              children: [
                Expanded(
                  child: OutlinedButton(
                    onPressed: () {
                      Navigator.pop(context);
                      _nameController.clear();
                      _amountController.clear();
                    },
                    style: OutlinedButton.styleFrom(
                      padding: const EdgeInsets.symmetric(vertical: 16),
                      side: BorderSide(
                        color: const Color(0xFF8E8E93),
                        width: 1,
                      ),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                    ),
                    child: Text(
                      l10n.cancel ?? 'İptal',
                      style: GoogleFonts.inter(
                        fontSize: 14,
                        fontWeight: FontWeight.w600,
                        color: const Color(0xFF8E8E93),
                      ),
                    ),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: ElevatedButton(
                    onPressed: _canSave() ? _saveSubscription : null,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: _canSave()
                          ? const Color(0xFFFF453A)
                          : (isDark
                              ? const Color(0xFF38383A)
                              : const Color(0xFFE5E5EA)),
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(vertical: 16),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                      elevation: 0,
                    ),
                    child: _isSaving
                        ? const SizedBox(
                            width: 18,
                            height: 18,
                            child: CircularProgressIndicator(
                              color: Colors.white,
                              strokeWidth: 2,
                            ),
                          )
                        : Text(
                            l10n.save ?? 'Kaydet',
                            style: GoogleFonts.inter(
                              fontSize: 14,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 20),
          ],
        ),
      ),
    );
  }

  // Get account display name (using getDisplayName like transaction form)
  String _getAccountDisplayName(AccountModel account, AppLocalizations l10n) {
    if (account.type == AccountType.cash) {
      // For cash, use cashWallet localization
      return l10n.cashWallet;
    } else {
      // For cards, clean name and add card type
      String cleanName = account.name
          .replaceAll(RegExp(r'\s*(Credit Card|Kredi Kartı|Debit Card|Banka Kartı)\s*$', caseSensitive: false), '')
          .trim();
      
      if (cleanName.isEmpty && account.bankName != null) {
        final cardType = account.type == AccountType.credit 
            ? l10n.creditCard
            : l10n.debitCard;
        return '${account.bankName} $cardType';
      }
      
      if (cleanName.isEmpty) {
        return account.type == AccountType.credit 
            ? l10n.creditCard
            : l10n.debitCard;
      }
      
      final cardType = account.type == AccountType.credit 
          ? l10n.creditCard
          : l10n.debitCard;
      return '$cleanName $cardType';
    }
  }

  // Get balance text for account
  String _getBalanceText(AccountModel account, ThemeProvider themeProvider, AppLocalizations l10n) {
    switch (account.type) {
      case AccountType.cash:
        return themeProvider.formatAmount(account.balance);
      case AccountType.credit:
        // For credit cards, show available limit
        final available = account.availableAmount;
        return '${themeProvider.formatAmount(available)} ${l10n.available}';
      case AccountType.debit:
        return themeProvider.formatAmount(account.balance);
    }
  }

  Widget _buildAccountOption({
    required BuildContext context,
    required AccountModel account,
    required bool isSelected,
    required AppLocalizations l10n,
    required ThemeProvider themeProvider,
    required VoidCallback onTap,
    bool isHorizontal = false,
  }) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final title = _getAccountDisplayName(account, l10n);
    final balanceText = _getBalanceText(account, themeProvider, l10n);

    if (isHorizontal) {
      // Ultra minimal horizontal card design
      return SizedBox(
        width: 140,
        child: Container(
          decoration: BoxDecoration(
            color: isSelected
                ? (isDark ? const Color(0xFF2C2C2E) : const Color(0xFFF2F2F7))
                : (isDark ? const Color(0xFF1C1C1E) : Colors.white),
            borderRadius: BorderRadius.circular(12),
            border: Border.all(
              color: isSelected
                  ? (isDark ? Colors.white.withOpacity(0.15) : const Color(0xFF6D6D70))
                  : (isDark ? const Color(0xFF3A3A3C) : const Color(0xFFE5E5EA)),
              width: isSelected ? 1.5 : 1,
            ),
          ),
          child: Material(
            color: Colors.transparent,
            child: InkWell(
              onTap: onTap,
              borderRadius: BorderRadius.circular(12),
              child: Padding(
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    // Account name
                    Text(
                      title,
                      style: GoogleFonts.inter(
                        fontSize: 14,
                        fontWeight: FontWeight.w600,
                        color: isDark ? Colors.white : Colors.black,
                        letterSpacing: -0.2,
                        height: 1.3,
                      ),
                      maxLines: 2,
                      overflow: TextOverflow.ellipsis,
                    ),
                    const SizedBox(height: 4),
                    // Balance
                    Text(
                      balanceText,
                      style: GoogleFonts.inter(
                        fontSize: 11,
                        fontWeight: FontWeight.w500,
                        color: isDark
                            ? const Color(0xFF8E8E93)
                            : const Color(0xFF6D6D70),
                        letterSpacing: -0.1,
                        height: 1.2,
                      ),
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      );
    }
    
    // Fallback (should never reach here)
    return const SizedBox.shrink();
  }
}
